name: Pull Request Approve
on:
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ main ]


permissions:
  contents: read

jobs:
  approve:
    runs-on: ubuntu-latest
    steps: 
      - id: get-members
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ORG_SLUG: ${{ github.repository_owner }}
          TEAM_SLUG: ApproveTeam
          ROLE: all
        run: |
          node main.js
      
      - id: echo-members
        run: |
          echo "${{ github.repository_owner }} ${{ steps.get-members.outputs.secret-number }}"